name: Renovate

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: renovate/renovate:43
    steps:
      - name: Run Renovate
        run: renovate
        env:
          RENOVATE_PLATFORM: forgejo
          RENOVATE_ENDPOINT: https://git.greil.fr/api/v1
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_REPOSITORIES: mat/homeassistant-comwatt
          GITHUB_COM_TOKEN: ${{ secrets.GITHUB_COM_TOKEN }}
          LOG_LEVEL: info
